language: ruby
rvm:
- 2.6.3
before_install: gem install bundler -v 2.0.2
services:
  - postgresql
before_script:
  - psql -c 'create database koroibos_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake import:olympic_data

script:
- bundle exec rspec
